In [1]:
from __future__ import print_function
import torch

Create a tensor matrix of $5\times3.

In [2]:
x = torch.Tensor(5, 3)
print(x)

tensor([[ 0.0000e+00,  1.5846e+29,  0.0000e+00],
        [ 1.5846e+29,  1.6897e+22,  1.1259e+24],
        [ 1.7753e+28,  1.7110e+19, -6.9857e+26],
        [ 4.5915e-41, -6.9857e+26,  4.5915e-41],
        [ 0.0000e+00,  1.5846e+29,  4.9203e-23]])


Print the size of the tensor $x$.

In [3]:
print(x.size())

torch.Size([5, 3])


Create another tensor matrix of $5\times3$.

In [4]:
y = torch.rand(5, 3)

torch.add() adds the two matrices.

In [5]:
print(torch.add(x, y))

tensor([[ 9.8379e-01,  1.5846e+29,  9.7935e-02],
        [ 1.5846e+29,  1.6897e+22,  1.1259e+24],
        [ 1.7753e+28,  1.7110e+19, -6.9857e+26],
        [ 2.5563e-01, -6.9857e+26,  2.7956e-01],
        [ 4.2113e-01,  1.5846e+29,  5.3117e-01]])


Create a third tensor matrix of $5\times3$, we will use this to store the result of addition

In [6]:
result = torch.Tensor(5, 3)

torch.add() will now add the two matrices and store the result in the variable $result$.

In [7]:
torch.add(x, y, out=result)
print(result)

tensor([[ 9.8379e-01,  1.5846e+29,  9.7935e-02],
        [ 1.5846e+29,  1.6897e+22,  1.1259e+24],
        [ 1.7753e+28,  1.7110e+19, -6.9857e+26],
        [ 2.5563e-01, -6.9857e+26,  2.7956e-01],
        [ 4.2113e-01,  1.5846e+29,  5.3117e-01]])


torch also supports in place addition using the .add_() function. Here $x$ is added to $y$ and the result is stored back in $y$.

In [8]:
y.add_(x)
print(y)

tensor([[ 9.8379e-01,  1.5846e+29,  9.7935e-02],
        [ 1.5846e+29,  1.6897e+22,  1.1259e+24],
        [ 1.7753e+28,  1.7110e+19, -6.9857e+26],
        [ 2.5563e-01, -6.9857e+26,  2.7956e-01],
        [ 4.2113e-01,  1.5846e+29,  5.3117e-01]])


torch vectors support numpy-like indexing and splicing. 

In [9]:
print(x[:, 1])

tensor([ 1.5846e+29,  1.6897e+22,  1.7110e+19, -6.9857e+26,  1.5846e+29])


Create a 1D tensor of $n$ (here 5) ones.

In [10]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


Use the .numpy() function to convert to a numpy array.

In [11]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


If only one number is passed to the .add_() function, it adds it to all elements in that vector (like in R).

In [12]:
a.add_(1)
print(a)

tensor([2., 2., 2., 2., 2.])


The tensor is now bound to the numpy variable, if one changes the other will also change

In [13]:
print(b)

[2. 2. 2. 2. 2.]


We see here that the value of $b$ also changes as the value of a changes

What if we want to read an numpy array into a torch Variable?

In [14]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)

The .from_numpy() function reads the data from a numpy array to a torch tensor.

In [15]:
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


As we can see the persistance of values remains between the numpy array $a$ and the torch tensor $b$.

We can run parts of our code on the GPU. This means that we have the flexibility to choose which parts of our code run on the CPU and which parts run on the GPU. 

Once we call the .cuda() function, the data is loaded on the gpu and the calculations on that variable will henceforth be run on the GPU.

In [17]:
if torch.cuda.is_available():
    print('Y')
    x = x.cuda()
    y = y.cuda()
    print(x + y)

We must keep in mind that there is an overhead of loading the data on the GPU. However, since the GPU performs matrix calculations much faster due to the parallelism it makes sense to use the GPU for parts of the program that have a good degree of parallelism. 

Note: For calculations between two Variables on the GPU, both the variables must be loaded on the GPU. Thus both $x$ and $y$ had to be loaded onto the GPU.